version: '3'

tasks:
  build:
    cmds:
      - mkdir -p out
      - cd package && crossplane xpkg build --package-file ../out/cloudflare-dns.xpkg
      - cd package && crossplane xpkg push --package ../out/cloudflare-dns.xpkg $REGISTRY/$IMAGE_NAME:$GITHUB_SHA